#!/bin/zsh

DOTFILES=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
ln -sf $DOTFILES/zsh/custom_plugins $HOME/.oh-my-zsh/custom/plugins

#ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

#ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig // not ready for this until I understand what it does

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
