if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=~/.config/composer/vendor/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    local
)

source $ZSH/oh-my-zsh.sh

# User configuration

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias zshconfig="vim ~/.zshrc"
alias zsource="source ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias tmuxconfig="vim ~/.tmux.conf"
alias gdiff="git diff master..$(git_current_branch) | grep \"^diff.*php$\""
alias test="phpunit-watcher watch --filter="
alias web2local="~/./ngrok http 8000"
alias ll='tail -f -n100 storage/logs/`ls -t storage/logs/ | head -1`'
alias sku="sudo su - sku"
alias artisan="php artisan"
alias byebatch="php artisan queue:prune-batches --unfinished=1"
alias publish="curl -F file=@- https://publish.ip1.cc"
alias dotfiles="cd ~/dotfiles"

function artisan: {
	php artisan | grep $1
}

function addalias {
        echo "alias $1" >> ~/.zshrc
}

function newbranch {
	git checkout master
	git checkout -b SKU-$1
}
